### PR TITLE
Global canopy

### LINKED ISSUE #72: Adding Holistic Python Script for Generating Global Canopy Inputs
Based on @angehung5 global canopy files Python script, as input to canopy-app (_GMU Hopper: /groups/ESS/whung/canopy_wind/global_canopy_gen.py_), it would be good if we  can revise to include methods in the script to generally complete following pre-processing steps for global canopy-app:

1) Use wget to retrieve the hourly 13 km GFSv16 meteorology files from AWS for specified times:   _wget --no-check-certificate --no-proxy https://nacc-in-the-cloud.s3.amazonaws.com/inputs/YYYYMMDD/gfs.t12z.sfcfHHH.nc_,

2) Use wget to retrieve climatological monthly canopy files with canopy (lai, clu, fch, and frt) and external variables used in canopy-app (frp, mol, csz, and href):   _wget --no-check-certificate --no-proxy https://nacc-in-the-cloud.s3.amazonaws.com/inputs/geo-files/gfs.canopy.t12z.2022MM01.sfcf000.nc_ 

3) Perform steps to append correct monthly climatological canopy variables (lai, clu, fch, and frt) from Step 2 to the hourly GFSv16 files matching correct months,

4) Perform steps to calculate date/time dependent external variables (mol and csz) and update the modified hourly GFSv16 files from Step 2-3.  Also ensure that the constant href (10 meter) variable is copied to each GFS file for dates/times, and

5) Check local directory (or possible FTP server) for NOAA's GBBEPx FRP data for the correct hourly dates/times and, if present update files from Step 4 for the correct FRP values.  If not present, use the example 12 month climatology (with warning printed that fires/FRP will not be respective of actual conditions).    This is OK if users don't need the limited WAF application for fires.

Then, we can provide this script on the GH repo, and will be instrumental in helping others generate global canopy inputs for canopy-app (for any given date/time (back to March 21, 2021 -- Start of the GFSv16 data record on AWS).  We could add the script to the _https://github.com/noaa-oar-arl/canopy-app/tree/develop/python_ directory.

### PR DESCRIPTION
**Pull request by drnimbusrain**
@zmoon @angehung5 Starting a draft PR for this. Do you want to add the CLI for the script?

### CODE REVIEW

**Comment by drnimbusrain** [comment]
@zmoon @angehung5 I have moved this to an active PR.  Do you want to convert back to draft for a CLI in the script, or should we move forward?

**Comment by zmoon** [comment]
Let me try it quickly tomorrow, or I'll review otherwise.

**Review by zmoon — APPROVED** [review]

**Comment by zmoon** [comment]
Can always add CLI later

**Comment by drnimbusrain** [comment]
Thanks Zach, agreed.  This is good as we can move forward with the tutorial highlighting this capability.

**Pull request merged**
