### PR TITLE
More explicit M17 way of calculating Uc with Eq. 10 and 14.

### PR DESCRIPTION
**Pull request by drnimbusrain**
This method simply combines Eq. 10 and 14 from Massman et al. 2017 to calculate the Uc, which may result in changes too.  @angehung5 Can you test this?

### CODE REVIEW

**Comment by angehung5** [comment]
Below is the comparison of wind profiles using original calculation and M17 formulation. M17 does better at Uc estimation and probably better at in-canopy wind, but the above-canopy wind speeds are way higher. Also the discontinuity at the canopy top is more significant when using M17. 

I am not sure which approach is better. The original calculation has larger bias in terms of Uc but the overall profile is ok and more smooth. M17 has better performance in Uc but the shape of the overall wind profile is kind of strange. 

xTE_wind_profile_0600_20200601_20200930_avg_sensitivity_uc_zh

**Comment by drnimbusrain** [comment]
Seems new M17 approach is overall better here,  and I don't see a greater
discontinuity (maybe a bit sharper).  What do other sites show, and for
those that have above canopy?  I agree its definitely higher in new M17
approach.

Thanks

**Comment by angehung5** [comment]
Seems the Uc estimation based on M17 works fine at Bartlett forest but is much higher at Chestnut, GoAmazon and Willow Creek, as well as above-canopy wind speeds. I would suggest sticking to current approach. 

Presentation1

**Comment by drnimbusrain** [comment]
@angehung5 OK, I agree, its too high.  Sorry, but made another slight change to this M17 approach, which should lower it now.  Can you check once more these results at four sites?  Thank you!

**Comment by drnimbusrain** [comment]
Sorry, made another change for the zpd calculation to be consistent with updated M17 method.  Please check now after latest commit.

**Comment by drnimbusrain** [comment]
@angehung5  Closing this for now, as we will remain with original approach for now, and work on this in future for more robust unified stability/RSL approach following Bonan.

**Pull request closed without merging**
