### PR TITLE
Gamma sm 

### LINKED ISSUE #113: [Biogenics]  Add Soil Moisture Gamma
@MaggieMarvin 
As discussed, we will need to also add a soil moisture gamma factor into the biogenic emissions (for isoprene only), which will be based on the GWETROOT = degree of saturation or wetness in the root-zone (top meter of soil). This is defined as the ratio of the volumetric soil moisture to the porosity.  This can be calculated from input GFS soil moisture (Noah and Noah-MP models include four soil layers, centred at 5, 25, 70, and 150 cm).
```
        float soilw1(time, grid_yt, grid_xt) ;
                soilw1:long_name = "volumetric soil moisture 0-10cm" ;
                soilw1:units = "fraction" ;
                soilw1:missing_value = 9.99e+20f ;
                soilw1:_FillValue = 9.99e+20f ;
                soilw1:cell_methods = "time: point" ;
                soilw1:output_file = "sfc" ;
        float soilw2(time, grid_yt, grid_xt) ;
                soilw2:long_name = "volumetric soil moisture 10-40cm" ;
                soilw2:units = "fraction" ;
                soilw2:missing_value = 9.99e+20f ;
                soilw2:_FillValue = 9.99e+20f ;
                soilw2:cell_methods = "time: point" ;
                soilw2:output_file = "sfc" ;
        float soilw3(time, grid_yt, grid_xt) ;
                soilw3:long_name = "volumetric soil moisture 40-100cm" ;
                soilw3:units = "fraction" ;
                soilw3:missing_value = 9.99e+20f ;
                soilw3:_FillValue = 9.99e+20f ;
                soilw3:cell_methods = "time: point" ;
                soilw3:output_file = "sfc" ;
        float soilw4(time, grid_yt, grid_xt) ;
                soilw4:long_name = "volumetric soil moisture 100-200cm" ;
                soilw4:units = "fraction" ;
                soilw4:missing_value = 9.99e+20f ;
                soilw4:_FillValue = 9.99e+20f ;
                soilw4:cell_methods = "time: point" ;
                soilw4:output_file = "sfc" 
```

I think we can initially follow MEGANv2 in HEMCO: https://github.com/geoschem/HEMCO/blob/main/src/Extensions/hcox_megan_mod.F90#L2467, or use MEGANv3 soil moisture corrections.

To get the volumetric soil moisture in top meter of soil, we can average the first three layers soilw1, soilw2, and soilw3, but need to get porosity to get GWETROOT, which can be associated with soil types, also available in the GFS data:

```
float sotyp(time, grid_yt, grid_xt) ;
                sotyp:long_name = "soil type in integer 1-9" ;
                sotyp:units = "number" ;
                sotyp:missing_value = 9.99e+20f ;
                sotyp:_FillValue = 9.99e+20f ;
                sotyp:cell_methods = "time: point" ;
                sotyp:output_file = "sfc" ;
```

Alternatively, as discussed in [Guenther et al. 2006 and shown in Eqs 20a-c](https://acp.copernicus.org/articles/6/3181/2006/), we can use the wilting point instead of porosity, which is available in the GFS data too, and use a PFT dependent root depth fraction (see Eq. 2 and Table 2 in [Zeng 2001](https://journals.ametsoc.org/view/journals/hydr/2/5/1525-7541_2001_002_0525_gvrdfl_2_0_co_2.xml)) and all soil levels to calculate the weighted average gamma soil moisture to use here.  I favor this approach as it can be used across any soil layer depths in model or observations.
```
float wilt(time, grid_yt, grid_xt) ;
                wilt:long_name = "wiltimg point (volumetric)" ;
                wilt:units = "Proportion" ;
                wilt:missing_value = 9.99e+20f ;
                wilt:_FillValue = 9.99e+20f ;
                wilt:cell_methods = "time: point" ;
                wilt:output_file = "sfc" ;
```

@angehung5 After we get this working in canopy-app using the already included four soil moisture parameters and the soil type or wilting point (dependent on approach) in the GFS sfc NetCDF files, we will need to add similar columns in the text files for example SE files in the GH repo.

### PR DESCRIPTION
**Pull request by drnimbusrain**
@MaggieMarvin I have a draft branch and PR here for the gamma soil activity factor (for isoprene only), which depends on input soil moisture (in four layers) and wilting point, along with a PFT dependent cumulative root fraction used for the final weighted average gamma soil.  You can please test this impact on biogenic isoprene emissions independently of my other branch/PR for historical effects.  Thank you!

@angehung5 If you please can see the SE domain example gfs .NC files.  I have added "soilw[1-4]" volumetric soil moistures and the "wilt" wilting points as inputs to canopy-app.  Can you add the corresponding five variables ("soilw[1-4]"  and "wilt") from the example .NC files as appended columns and to the example .TXT files?

You can see that it breaks the CI because the usual .txt check fails without these variables in the files.

This includes updates to the following:

gfs.t12z.20220630.sfcf023.canopy.txt
gfs.t12z.20220701.sfcf000.canopy.txt
gfs.t12z.20220701.sfcf001.canopy.txt
point_file_20220630.sfcf023.txt
point_file_20220701.sfcf000.txt
point_file_20220701.sfcf001.txt

 You can share with me their location for me to add to this branch for functionality when using text files, or could create a PR back to this [gamma_sm] branch for updating the text files.  

Thank you!

### CODE REVIEW

**Comment by drnimbusrain** [comment]
This is currently a draft and needs thorough testing:

- [x] Test impacts of gamma soim for isoprene emissions against MEGANv2 and MEGANv3
- [ ] Evaluate impacts of gamma soim for isoprene against PECORINO campaign

**Comment by angehung5** [comment]
@drnimbusrain Files updated. You can also find them on Hopper: /groups/ESS/whung/canopy_wind/gfsv16_test_data

**Comment by drnimbusrain** [comment]
> @drnimbusrain Files updated. You can also find them on Hopper: /groups/ESS/whung/canopy_wind/gfsv16_test_data

Thank you @angehung5   Seems it fixes the CI too since you added those variables to the text files.  @MaggieMarvin [is testing it using netcdf files against MEGAN](https://docs.google.com/presentation/d/1ctHRwjB0bUrs0W67sQqSZnZ4M559UTfhiEI0DKyr5Vw/edit#slide=id.g2b94b3a8c6d_0_65) and seems to be working appropriately.  I will test your .txt files to make sure too.

**Review by MaggieMarvin — APPROVED** [review]
Looks good after bug fix! Evaluated for 08/01/2021 1800 UTC - when turned on reduces isoprene emissions mainly over croplands by up to about 50% and improves agreement slightly with MEGAN. Input data on soil moisture and wilting point looks reasonable, and gamma factor behaves as expected. In future may want to consider MEGANv3 parameterization and expanding to other species.
map_canopyapp_bio_NA-12

**Comment by drnimbusrain** [comment]
Thank you Maggie!!  Can you elaborate on the MEGAN3 gamma soil moisture
approach for all species?  Can we still use soil moisture and wilting point
inputs?

**Comment by MaggieMarvin** [comment]
MEGANv3 has an option to calculate gamma_sm using a photosynthesis parameter and soil wetness factor from a CLM but this may not be straightforward to implement in canopy-app. MEGANv3 otherwise uses the same parameterization from Guenther 2006 but my understanding is that it only applies soil moisture from the top layer and changes delta_theta1 to 0.04. Overall this should reduce isoprene emissions further (particularly over croplands) in our test case of 08/01/2021 1800 UTC because gamma_sm = 1 at the lowest soil layer, which is weighted more than the other layers in our current implementation.

**Comment by MaggieMarvin** [comment]
As far as I can tell, gamma_sm is applied to all species in MEGANv3.

**Comment by drnimbusrain** [comment]
> As far as I can tell, gamma_sm is applied to all species in MEGANv3.

@MaggieMarvin OK, as discussed I now changed code to allow for gamma_sm applied to all species here in canopy-app too.  Let me know if you are still good, and I will merge.

**Comment by drnimbusrain** [comment]
@MaggieMarvin Merging...

**Pull request merged**
