### PR TITLE
Python runner

### PR DESCRIPTION
**Pull request by zmoon**
Python module to run canopy-app and autoload output with xarray.

Will help with #24

todo:
* [x] validate config (at least keys)
* [x] sensitivity helper (namelist options)
* [x] able to run the point case
* [x] `verbose`
* [x] readme for `python` dir
* Binder config (~~maybe~~ for separate PR, with notebook examples including plotting and such)

### CODE REVIEW

**Comment by drnimbusrain** [comment]
@zmoon These look like great features!  Looking forward to updated README with examples for running the python dir.  Do we want to add simple py plotting/analysis to this as well?  Are you envisioning this to run automatically with new commits/PRs?  

Thank you!

**Comment by zmoon** [comment]
>  examples for running the python dir

You can try it out right now if you want, e.g.
```
cd python
ipython -i run.py
ds.<something>
...
```

> Are you envisioning this to run automatically with new commits/PRs?

Yes but also for us to use.

> Do we want to add simple py plotting/analysis to this as well? 

Yeah I will set up some notebook examples.

**Comment by zmoon** [comment]
Maybe should add a reference to the Python readme in the main readme.

**Review by drnimbusrain — APPROVED** [review]

**Comment by drnimbusrain** [comment]
@zmoon Yes, I would add some description/reference in the main README.  Other than that, I tested and I really like this start to python functionality!

**Pull request merged**
