### PR TITLE
Feature/netcdf

### PR DESCRIPTION
**Pull request by drnimbusrain**
This PR addresses issues #22 and #25 , and creates tested option to both input either 1D txt or 2D netcdf files, as well as include an output 2D netcdf file (only when a 2D netcdf input file is used).  There is a new namelist option (`infmt_opt`) needed, which is default = 0, indicating that a 2D netcdf input file is used, and thus the output is both 1D text files as well as a 2D NetCDF file.  If `infmt_opt` = 1, this indicates that the input file is only a 1D txt file, and thus the output will only include 1D text files accordingly. 

Also, added/modified two new namelist options (`href_opt` and `href_set`), which allows user to either use the `href_set` value from namelist (`href_opt`=0; default), or take the HREF values from a 2D NetCDF input file (`href_opt`=1), since the HREF variable is now available in 2D netcdf file.   

Finally, please note that this now requires Canopy-App to use NetCDF/NetCDF-Fortran compiled libraries (e.g., on Hopper:  /opt/sw/spack/apps/linux-centos8-cascadelake/gcc-9.3.0-openmpi-4.0.4/netcdf-c-4.7.4-vh), and thus the CI/Build-test checks here will inherently fail.   @zmoon I don't know if there is a way to update the CI (`.github/workflows/ci.yml`) to include the NetCDF library dependence of Canopy-App.

### CODE REVIEW

**Comment by zmoon** [comment]
We will need to update the CI to get netcdf/netcdff in order to test. I will look into that.

**Comment by zmoon** [comment]
@drnimbusrain do you mind if I move the orphan subroutines to module first?

**Comment by drnimbusrain** [comment]
Zach,

I agree.  Please do that for anything that needs it, as it is a huge help.
 Thanks!!

Patrick

**Comment by zmoon** [comment]
Building (and running) without netcdf currently don't work. Is that ok? Or do we want to fix that first?

**Comment by drnimbusrain** [comment]
I am somewhat ok with it not working without NetCDF, as it was easiest to
implement and seemed like most would want to use NetCDF anyway.

But, I agree it would be nice to have it as an option if you want to take a
crack at fixing it, I appreciate it Zach!

Patrick

**Comment by drnimbusrain** [comment]
@zmoon   Can you work on adding the NetCDF purely as an option to compile/run?  I know this requires code changes too to isolate the "netcdf" dependent routines.

**Comment by zmoon** [comment]
@drnimbusrain I addressed it, let me know what you think

**Comment by drnimbusrain** [comment]
Zach,  you're awesome!  I'll test it.

**Comment by drnimbusrain** [comment]
@zmoon OK I have tested your netcdf updates.  First, it seems like default is NETCDF=1, thus requiring netcdf libraries.  I am OK with this being the default, but just wanted to make sure that was your intention. 

**Test 1,  NetCDF Off -- 1D Text and 2D NetCDF Input Test:**  
- Compile:  DEBUG=1 NETCDF=0 make;  OK, compiles with no warnings
- Run:  1D  input_variables.txt and input_variables_point.txt run; OK, model has good output
- Run:  2D input_variables_2D.nc;  OK, model expectedly fails as without netcdf.

**Test 1,  NetCDF On -- 1D Text and 2D NetCDF Input Test:**  

- Compile:  DEBUG=1 NETCDF=1 make;  Compiles, but has warnings of unused functions:
- cascadelake/gcc-9.3.0-openmpi-4.0.4/netcdf-fortran-4.5.3-ff/include -c canopy_ncf_io_mod.F90
canopy_ncf_io_mod.F90:50:0:
   50 |     SUBROUTINE get_var_3d_real_cdf (cdfid, var, dum3d, it, rcode)
      |
Warning: ‘get_var_3d_real_cdf’ defined but not used [-Wunused-function]
canopy_ncf_io_mod.F90:87:0:
   87 |     SUBROUTINE get_var_3d_int_cdf (cdfid, var, idum3d, it, rcode)
      |
Warning: ‘get_var_3d_int_cdf’ defined but not used [-Wunused-function]
canopy_ncf_io_mod.F90:234:0:
  234 |     SUBROUTINE get_var_1d_double_cdf (cdfid, var, dum1d, it, rcode)
      |
Warning: ‘get_var_1d_double_cdf’ defined but not used [-Wunused-function]
canopy_ncf_io_mod.F90:263:0:
  263 |     SUBROUTINE get_var_real_cdf (cdfid, var, scalar, rcode)
      |
Warning: ‘get_var_real_cdf’ defined but not used [-Wunused-function]

I comment these out right now as they are not being used.  See latest commit:  

- Run:  1D  input_variables.txt and input_variables_point.txt run; OK, model has good output
- Run:  2D input_variables_2D.nc;  OK, model has good output

I think this is great Zach, and nearly ready to merge with develop-->master.  Thank you!!

**Comment by zmoon** [comment]
> seems like default is NETCDF=1, thus requiring netcdf libraries. I am OK with this being the default, but just wanted to make sure that was your intention.

👍 

> nearly ready to merge with develop-->master

👍

**Comment by drnimbusrain** [comment]
@zmoon If there is no further objection, I am going to merge --> develop --> master.  Thank you.

**Pull request merged**
