### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by drnimbusrain**

### CODE REVIEW

**Review by zmoon — APPROVED** [review]
Looks fine but I'm not in love with the name `pai_set`.

**Comment by drnimbusrain** [comment]
@zmoon Thank you Zach.  What do you suggest to change these to?

**Comment by zmoon** [comment]
Couldn't think of anything good for `pai_set`. For the `rk` I meant in the namelist reading subroutine change `real` to `real(rk)` ?

**Comment by drnimbusrain** [comment]
@zmoon Can you check again on my usage of rk for pai_set?  You are correct that it had an issue with the way I had it before.  I remove the rk now for this.

**Comment by zmoon** [comment]
I'll check it out later. Don't know why couldn't just use `real(rk)` for it everywhere.

**Comment by drnimbusrain** [comment]
@zmoon OK, yes.  I make now all namelist real variables to rk consistently.  This should be better.

**Pull request merged**
