### PR TITLE
Fix examples

### LINKED ISSUE #110: [CI] Notebook failure doesn't fail CI?
> I see that although for 30eea0b there was an error when running the nb, it didn't fail CI. I should fix that. Probably need to check the rc in the loop and exit if nonzero.

_Originally posted by @zmoon in https://github.com/noaa-oar-arl/canopy-app/issues/109#issuecomment-1930754165_

Also when it did fail (should have, for invalid namelist key), the error message was from a later cell, will have to investigate that as well.

### PR DESCRIPTION
**Pull request by zmoon**
closes #110

### CODE REVIEW

**Comment by zmoon** [comment]
Yay now it correctly fails. Still gotta actually fix the examples though...

**Comment by zmoon** [comment]
@drnimbusrain any new features to highlight in the 1-D examples?

**Comment by drnimbusrain** [comment]
> @drnimbusrain any new features to highlight in the 1-D examples?

@zmoon Thank you for working on these updates!  Most recently we have been working on the biogenic emissions, and have added a number of new options that I think could be added and useful for 1-D examples.  See the new biogenic options, ```loss_opt```,  ```leafage_opt```,```hist_opt```, and ```soim_opt```.

**Comment by zmoon** [comment]
@drnimbusrain I think we can address that in a separate PR, keep this one simple.

**Review by drnimbusrain — APPROVED** [review]

**Pull request merged**
